# Generated by Django 5.0.7 on 2024-08-21 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0009_appointment_agora_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_mentor_joined', models.BooleanField(default=False)),
                ('is_user_joined', models.BooleanField(default=False)),
                ('call_start_time', models.DateTimeField(blank=True, null=True)),
                ('call_end_time', models.DateTimeField(blank=True, null=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='call_status', to='mentor.appointment')),
            ],
        ),
    ]
